dist: trusty
root: required
language: java

os:
  - linux

env:
  - V=2.0.0

before_install:
  - OS=linux
  - ARCH=x86_64
  - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$V"
  - GH_ARTIFACT="bazel-$V-installer-$OS-$ARCH.sh"
  - URL="$GH_BASE/$GH_ARTIFACT"
  - echo $URL
  - wget -O install.sh $URL
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

script:
  - bazel build -k //...
  # - bazel --bazelrc=tools/bazel.travis.rc test -k //...
  # - format/run --verify
  # - sync-deps/run --verify
  # - ./integration-test